
### get all users
GET http://localhost:4000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDU3MDE4NjQsImV4cCI6MTcwNTc4ODI2NH0.t4vnATmaqd83EBqXLjSJ3MKIbuUMGcFWW45ESh8m6b4


### get user by id

GET http://localhost:4000/users/2

### create user

POST  http://localhost:4000/users/

{
    "name": "jonhatan",
    "email": "johatan@gmail.com"
}
