
### get all users
GET http://localhost:4000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDQ1NjMxOTQsImV4cCI6MTcwNDY0OTU5NH0.SYkX_wvjBbYuY-fdgxgsTeDxdHkx_bdeKau9twxaJHc

### get user by id

GET http://localhost:4000/users/2

### create user

POST  http://localhost:4000/users/

{
    "name": "jonhatan",
    "email": "johatan@gmail.com"
}
